name: Trigger Action on a CRON Schedule
on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  python-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          python -m pip install -r requirements.txt
          python scrape.py

    - name: Install dependencies
      run: pip install -r requirements.txt

      - name: Run python script
        run: scrape.py
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: file.txt